library(dplyr)
old_data <- read.csv("./Drafts/awards_metadata.csv")
#head(old_data)
filter_data <- filter(old_data, Winner!="NA")
#head(filter_data)
select_data <- select(filter_data, Year, Award, Name, Film)
#head(select_data)
movie_wins <- filter(select_data, Award=="Best Picture" | Award=="Best Motion Picture")
#head(filter_data_movie_wins)
movie_wins <- count(movie_wins, Name)
head(movie_wins)
actor_wins <- filter(select_data, Award=="Actor" | Award=="Actress" | Award=="Actor in a Leading Role" | Award=="Actress in a Leading Role" | Award=="Actor in a Supporting Role" | Award=="Actress in a Supporting Role")
#head(filter_data_actor_wins)
actor_wins <- count(actor_wins, Name)
head(actor_wins)
director_wins <- filter(select_data, Award=="Directing")
director_wins$Name = director_wins$Film
director_wins <- count(director_wins, Name)
head(director_wins)
#typeof(director_wins)
total_wins <- rbind(actor_wins,director_wins,movie_wins)
head(total_wins)