---
title: "MSFA_GroupG_Part1"
author: "Daisy"
date: "26/09/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

There are thousands of movies produced each year. In 2016, the number of films released in theater was 718, which was up 18 percent from ten years ago (MPAA, 2017). Some of those film are extremely popular and some of them are just heard by very few people. The revenue generated in this industry is tremendous. In 2016, the global box office for all films released in each country around the world reach¡ç38.6 billion(MPAA, 2017). But the box office of different movies varies too. The top 1 box office created by Finding Dory is¡ç4.9 billion, while the movie, Moonlight, only generated about ¡ç27 million box office (http://www.boxofficemojo.com/yearly/chart/?page=1&view=releasedate&view2=domestic&yr=2016&p=.htm). What makes the difference? How can we predict whether a movie is going to be popular or not? The answer to this problem can be fascinating and shed lights on the whole movie industry.

To answer these question, our group analyses an IMDB dataset of over 5000 movies download from the Kaggle website. (https://www.kaggle.com/deepmatrix/imdb-5000-movie-dataset). IMDB, The Internet Movie Database (IMDb; http://www.imdb.com), is one of the most frequently accessed website all around the world. It contains metadata on films, television programs, videos, and video games (Wasserman, 2014). We choose the movie produced by United States and choose English as the movie language. By working deep into this dataset, we try to figure out the relationship between revenue and movie genre, the number of film Facebook likes, IMDB rating, the popularity of actors, the popularity of directors, movie budget, film duration, number of voters and number of critic reviews,


Wasserman, M., Mukherjee, S., Scott, K., Zeng, X. H. T., & Radicchi, F. (2015). Correlations between user voting data, budget, and box office for films in the internet movie database. Journal of the Association for Information Science & Technology, 66(4), 858-868.



